analytics:
  beautify: false
  datetime: true
  datetime_format: '%Y-%m-%d %H:%M:%S.%f'
  path: reports
cache:
  item_time: 1209600
  path: cache
  target_time: 604800
catalog_worker:
  count: 12
  tick: 1.0
  wait: 7
event_handler:
  tick: 0.1
  wait: 3.0
logger:
  level: 4
  message_content: 2
  mode: 1
  utc_time: true
main:
  logs_path: logs
  production: false
  storage_path: storage
pipe:
  tick: 0.5
  wait: 10.0
priority:
  CInterval: 100
  CScheduled: 50
  CSmart: 10
  RTInterval:
  - 100
  - 100
  RTScheduled:
  - 50
  - 0
  RTSmart:
  - 10
  - 0
  TInterval:
  - 100
  - 100
  TScheduled:
  - 50
  - 0
  TSmart:
  - 10
  - 0
  catalog_default: 100
  target_default: 1001
provider:
  max_bad: 25
  proxy_timeout: 3.0
  test_url: http://google.com/
queues:
  catalog_queue_put_wait: 8.0
  catalog_queue_size: 256
  target_queue_put_wait: 8.0
  target_queue_size: 512
sub_provider:
  comp_type: gzip, deflate, br
  compression: false
  connect_timeout: 1.0
  max_redirects: 5
  max_retries: 3
  read_timeout: 2.0
thread_manager:
  lock_ticks: 16
  tick: 1.0
worker:
  count: 7
  tick: 1.0
  wait: 5.0
