analytics:
  beautify: false
  datetime: true
  datetime_format: '%Y-%m-%d %H:%M:%S.%f'
  path: reports
event_handler:
  tick: 1.0
  wait: 3.0
index_worker:
  count: 5
  tick: 1.0
  wait: 7
logger:
  level: 4
  message_content: 2
  mode: 1
  utc_time: true
main:
  cache_path: cache
  logs_path: logs
  production: false
pipe:
  success_hashes_time: 604800
  tick: 0.5
  wait: 10.0
priority:
  IInterval: 50
  IOnce: 10
  TInterval:
  - 100
  - 100
  TScheduled:
  - 50
  - 0
  TSmart:
  - 10
  - 0
  interval_default: 100
  target_default: 1001
provider:
  delay: 7.5
  max_bad: 25
  test_url: http://google.com/
  timeout: 3.0
queues:
  index_queue_put_wait: 8.0
  index_queue_size: 256
  target_queue_put_wait: 8.0
  target_queue_size: 512
thread_manager:
  lock_ticks: 16
  tick: 1.0
worker:
  count: 5
  tick: 1.0
  wait: 5.0
