analytics:
  beautify: false
  datetime: true
  datetime_format: '%Y-%m-%d %H:%M:%S.%f'
  path: reports
cache:
  item_time: 1209600
  path: cache
  target_time: 604800
catalog_worker:
  count: 5
  tick: 1.0
  wait: 7
event_handler:
  tick: 0.1
  wait: 3.0
logger:
  level: 4
  message_content: 2
  mode: 1
  utc_time: true
main:
  logs_path: logs
  production: false
pipe:
  tick: 0.5
  wait: 10.0
priority:
  CInterval: 100
  CScheduled: 50
  CSmart: 10
  RTInterval:
  - 100
  - 100
  RTScheduled:
  - 50
  - 0
  RTSmart:
  - 10
  - 0
  TInterval:
  - 100
  - 100
  TScheduled:
  - 50
  - 0
  TSmart:
  - 10
  - 0
  catalog_default: 100
  target_default: 1001
provider:
  delay: 7.5
  max_bad: 25
  test_url: http://google.com/
  timeout: 5.0
queues:
  catalog_queue_put_wait: 8.0
  catalog_queue_size: 256
  target_queue_put_wait: 8.0
  target_queue_size: 512
thread_manager:
  lock_ticks: 16
  tick: 1.0
worker:
  count: 5
  tick: 1.0
  wait: 5.0
