analytics:
  beautify: false
  datetime: true
  datetime_format: '%Y-%m-%d %H:%M:%S.%f'
  interval: 300
  path: reports
api:
  priority_IInterval: 50
  priority_IOnce: 10
  priority_TInterval:
    - 100
    - 100
  priority_TScheduled:
    - 50
    - 0
  priority_TSmart:
    - 10
    - 0
  priority_interval_default: 100
  priority_target_default: 1001
pipe:
  success_hashes_time: 604800
  tick: 0.5
  wait: 10
index_worker:
  count: 3
  tick: 1
  wait: 7
logger:
  level: 4
  message_content: 2
  mode: 1
  utc_time: true
main:
  cache_path: .cache
  logs_path: logs
  production: false
queues:
  index_queue_put_wait: 8
  index_queue_size: 256
  target_queue_put_wait: 8
  target_queue_size: 1024
thread_manager:
  tick: 1
worker:
  count: 3
  tick: 1
  wait: 5
