cache_folder: .cache
collector_tick: 0.1
collector_wait: 10
log_level: 3
log_mode: 1
log_utc_time: true
logs_folder: logs
production: false
success_hashes_time: 172800
target_queue_put_wait: 8
target_queue_size: 64
targets_hashes_size: 1024
task_queue_get_wait: 1
task_queue_put_wait: 8
task_queue_size: 64
worker_tick: 1
worker_wait: 5
workers_count: 3
