cache_folder: .cache
collector_tick: 0.5
collector_wait: 10
log_level: 4
log_mode: 1
log_utc_time: yes
logs_folder: logs
priority_TInterval:
  - 100
  - 100
priority_TScheduled:
  - 50
  - 0
priority_TSmart:
  - 10
  - 0
production: no
success_hashes_time: 172800
target_queue_put_wait: 8
target_queue_size: 512
targets_hashes_size: 1024
task_queue_put_wait: 8
task_queue_size: 512
worker_tick: 1
worker_wait: 5
workers_count: 3
